"""empty message

Revision ID: 3ec51f0e35bb
Revises: fd00762af4ff
Create Date: 2023-05-12 10:38:48.493836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec51f0e35bb'
down_revision = 'fd00762af4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pets_doctor_id_doctors', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pets_doctor_id_doctors', 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###
