"""empty message

Revision ID: 47d890080d01
Revises: 8d6996f14489
Create Date: 2023-05-09 10:16:53.560446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d890080d01'
down_revision = '8d6996f14489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
