"""empty message

Revision ID: 75018517036a
Revises: 32116b609977
Create Date: 2023-05-09 16:24:53.086124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75018517036a'
down_revision = '32116b609977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
