"""empty message

Revision ID: c4df706f7855
Revises: ed7731571cb0
Create Date: 2023-05-11 16:15:00.961054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4df706f7855'
down_revision = 'ed7731571cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.drop_column('pet_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
