"""empty message

Revision ID: ed7731571cb0
Revises: 75018517036a
Create Date: 2023-05-11 16:13:57.717223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7731571cb0'
down_revision = '75018517036a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_type', sa.String(), nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('weight')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('pet_type')

    # ### end Alembic commands ###
