"""empty message

Revision ID: fd00762af4ff
Revises: cdcff68c85df
Create Date: 2023-05-12 10:32:10.261359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd00762af4ff'
down_revision = 'cdcff68c85df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_owner_id_owners', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_owner_id_owners', 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###
